# Generated by Django 6.0.6 on 2026-07-05 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.SlugField(max_length=80, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('location', models.CharField(blank=True, default='', max_length=120)),
                ('category', models.CharField(blank=True, default='', max_length=60)),
                ('stream_path', models.CharField(help_text='MediaMTX path, e.g. live/gunadala_ps', max_length=200)),
                ('publish_user', models.CharField(blank=True, default='', max_length=80)),
                ('publish_pass', models.CharField(blank=True, default='', max_length=80)),
                ('stream_url', models.URLField(max_length=300)),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('error', 'Error')], default='offline', max_length=20)),
                ('error_type', models.CharField(blank=True, default='stream not found', max_length=120, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
    ]
