# Generated by Django 6.0.3 on 2026-07-05 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='comp_zone',
            field=models.CharField(default='SAFE', max_length=40),
        ),
        migrations.AddField(
            model_name='camera',
            name='people_count',
            field=models.IntegerField(default=0),
        ),
    ]
